# Generated by Django 5.2.8 on 2025-11-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answerlike_questionlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='detailed',
            new_name='text',
        ),
    ]
