# Generated by Django 5.2.8 on 2025-12-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_detailed_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
