# Generated by Django 5.2.8 on 2025-12-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
